/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import EstructuraS.ListaPersonas;
import ObjetosU.*;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author nahue
 */
public class PantallaINFO extends javax.swing.JFrame {
    int xMouseINFO,yMouseINFO;
    private DefaultListModel<String> modeloMaterias;
    //private JList<String> Lmateriascargadas1;
    /**
     * Creates new form PantallaINFO
     */
    public PantallaINFO(Persona p,ListaPersonas lista) {
        initComponents();

        modeloMaterias = new DefaultListModel<>();
        Lmateriascargadas1.setModel(modeloMaterias);

        mostrarPersona(p);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelINFO = new javax.swing.JPanel();
        HeaderINFO = new javax.swing.JPanel();
        LabDatos = new javax.swing.JLabel();
        eXitINFO = new javax.swing.JPanel();
        X = new javax.swing.JLabel();
        PcargauserINFO = new javax.swing.JPanel();
        nombre1 = new javax.swing.JLabel();
        documento1 = new javax.swing.JLabel();
        direccion1 = new javax.swing.JLabel();
        Tnombre1 = new javax.swing.JTextField();
        Tdocumento1 = new javax.swing.JTextField();
        fechanacimiento1 = new javax.swing.JLabel();
        Tdia1 = new javax.swing.JTextField();
        Tmes1 = new javax.swing.JTextField();
        Tanio1 = new javax.swing.JTextField();
        Tdireccion1 = new javax.swing.JTextField();
        Tfacultad1 = new javax.swing.JTextField();
        Tcarrera1 = new javax.swing.JTextField();
        facultad1 = new javax.swing.JLabel();
        carrera1 = new javax.swing.JLabel();
        Tmesing1 = new javax.swing.JTextField();
        Tanioing1 = new javax.swing.JTextField();
        fechaingreso1 = new javax.swing.JLabel();
        Tdiaing1 = new javax.swing.JTextField();
        Stipopersona1 = new javax.swing.JComboBox<>();
        tipopersona1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();
        PtipouserINFO = new javax.swing.JPanel();
        Puseraccion1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Tregistro1 = new javax.swing.JTextField();
        Buttcargamaterias1 = new javax.swing.JButton();
        carrerapostgrado1 = new javax.swing.JLabel();
        SepRegist1 = new javax.swing.JSeparator();
        materia1 = new javax.swing.JLabel();
        registro1 = new javax.swing.JLabel();
        setmaterias1 = new javax.swing.JSeparator();
        cargo1 = new javax.swing.JLabel();
        Tcarrerapostgrado1 = new javax.swing.JTextField();
        Tmaterias1 = new javax.swing.JTextField();
        Tcargo1 = new javax.swing.JTextField();
        SepCarrera1 = new javax.swing.JSeparator();
        sepCargo1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Lmateriascargadas1 = new javax.swing.JList<>();
        Butteliminarmateria1 = new javax.swing.JButton();
        materiascargadas1 = new javax.swing.JLabel();
        Buttmodificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelINFO.setBackground(new java.awt.Color(255, 255, 255));
        PanelINFO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 139, 144)));
        PanelINFO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HeaderINFO.setBackground(new java.awt.Color(0, 139, 144));
        HeaderINFO.setForeground(new java.awt.Color(255, 255, 255));
        HeaderINFO.setToolTipText("");
        HeaderINFO.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        HeaderINFO.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderINFOMouseDragged(evt);
            }
        });
        HeaderINFO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HeaderINFOMouseClicked(evt);
            }
        });
        HeaderINFO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabDatos.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        LabDatos.setForeground(new java.awt.Color(255, 255, 255));
        LabDatos.setText("Datos");
        HeaderINFO.add(LabDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 67, -1));

        eXitINFO.setBackground(new java.awt.Color(0, 139, 144));
        eXitINFO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        eXitINFO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eXitINFOMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eXitINFOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eXitINFOMouseExited(evt);
            }
        });

        X.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        X.setForeground(new java.awt.Color(255, 255, 255));
        X.setText("X");

        javax.swing.GroupLayout eXitINFOLayout = new javax.swing.GroupLayout(eXitINFO);
        eXitINFO.setLayout(eXitINFOLayout);
        eXitINFOLayout.setHorizontalGroup(
            eXitINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
            .addGroup(eXitINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(eXitINFOLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(X)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        eXitINFOLayout.setVerticalGroup(
            eXitINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(eXitINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(eXitINFOLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(X)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        HeaderINFO.add(eXitINFO, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 50, 40));

        PanelINFO.add(HeaderINFO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 40));

        PcargauserINFO.setBackground(new java.awt.Color(255, 255, 255));
        PcargauserINFO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombre1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nombre1.setText("Nombre");
        PcargauserINFO.add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        documento1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        documento1.setText("Documento");
        PcargauserINFO.add(documento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        direccion1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        direccion1.setText("Direccion");
        PcargauserINFO.add(direccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        Tnombre1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tnombre1.setText("Ingrese su Nombre");
        Tnombre1.setBorder(null);
        Tnombre1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tnombre1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Tnombre1FocusLost(evt);
            }
        });
        Tnombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tnombre1ActionPerformed(evt);
            }
        });
        PcargauserINFO.add(Tnombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 260, -1));

        Tdocumento1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tdocumento1.setText("Ingrese su Documento");
        Tdocumento1.setBorder(null);
        Tdocumento1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tdocumento1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Tdocumento1FocusLost(evt);
            }
        });
        PcargauserINFO.add(Tdocumento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 260, -1));

        fechanacimiento1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fechanacimiento1.setText("Fecha de Nacimiento");
        PcargauserINFO.add(fechanacimiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        Tdia1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tdia1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tdia1.setText("Dia");
        Tdia1.setBorder(null);
        Tdia1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tdia1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Tdia1FocusLost(evt);
            }
        });
        PcargauserINFO.add(Tdia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 80, -1));

        Tmes1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tmes1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tmes1.setText("Mes");
        Tmes1.setBorder(null);
        Tmes1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tmes1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Tmes1FocusLost(evt);
            }
        });
        PcargauserINFO.add(Tmes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 80, -1));

        Tanio1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tanio1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tanio1.setText("Año");
        Tanio1.setBorder(null);
        Tanio1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tanio1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Tanio1FocusLost(evt);
            }
        });
        PcargauserINFO.add(Tanio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 80, -1));

        Tdireccion1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tdireccion1.setText("Ingrese su Direccion");
        Tdireccion1.setBorder(null);
        Tdireccion1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tdireccion1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Tdireccion1FocusLost(evt);
            }
        });
        Tdireccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tdireccion1ActionPerformed(evt);
            }
        });
        PcargauserINFO.add(Tdireccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 260, -1));

        Tfacultad1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tfacultad1.setText("Ingrese su Facultad");
        Tfacultad1.setBorder(null);
        Tfacultad1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tfacultad1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Tfacultad1FocusLost(evt);
            }
        });
        Tfacultad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tfacultad1ActionPerformed(evt);
            }
        });
        PcargauserINFO.add(Tfacultad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 260, -1));

        Tcarrera1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tcarrera1.setText("Ingrese su carrera");
        Tcarrera1.setBorder(null);
        Tcarrera1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tcarrera1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Tcarrera1FocusLost(evt);
            }
        });
        Tcarrera1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tcarrera1ActionPerformed(evt);
            }
        });
        PcargauserINFO.add(Tcarrera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 260, 20));

        facultad1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        facultad1.setText("Facultad");
        PcargauserINFO.add(facultad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 6, -1, -1));

        carrera1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        carrera1.setText("Carrera");
        PcargauserINFO.add(carrera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, 20));

        Tmesing1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tmesing1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tmesing1.setText("Mes");
        Tmesing1.setBorder(null);
        Tmesing1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tmesing1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Tmesing1FocusLost(evt);
            }
        });
        PcargauserINFO.add(Tmesing1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 80, 20));

        Tanioing1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tanioing1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tanioing1.setText("Año");
        Tanioing1.setBorder(null);
        Tanioing1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tanioing1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Tanioing1FocusLost(evt);
            }
        });
        PcargauserINFO.add(Tanioing1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 80, 20));

        fechaingreso1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fechaingreso1.setText("Fecha de Ingreso");
        PcargauserINFO.add(fechaingreso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        Tdiaing1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tdiaing1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tdiaing1.setText("Dia");
        Tdiaing1.setBorder(null);
        Tdiaing1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tdiaing1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Tdiaing1FocusLost(evt);
            }
        });
        Tdiaing1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tdiaing1ActionPerformed(evt);
            }
        });
        PcargauserINFO.add(Tdiaing1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 80, 20));

        Stipopersona1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Stipopersona1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un Tipo", "Alumno", "Alumno de Postgrado", "Docente" }));
        Stipopersona1.setBorder(new javax.swing.border.MatteBorder(null));
        Stipopersona1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Stipopersona1ActionPerformed(evt);
            }
        });
        PcargauserINFO.add(Stipopersona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        tipopersona1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tipopersona1.setText("Tipo de persona");
        PcargauserINFO.add(tipopersona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 89, 124));
        PcargauserINFO.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 260, 10));

        jSeparator14.setForeground(new java.awt.Color(0, 89, 124));
        PcargauserINFO.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 260, 10));

        jSeparator15.setForeground(new java.awt.Color(0, 89, 124));
        PcargauserINFO.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 80, 10));

        jSeparator16.setForeground(new java.awt.Color(0, 89, 124));
        PcargauserINFO.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 80, 10));

        jSeparator17.setForeground(new java.awt.Color(0, 89, 124));
        PcargauserINFO.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 80, 10));

        jSeparator18.setForeground(new java.awt.Color(0, 89, 124));
        PcargauserINFO.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 260, 10));

        jSeparator19.setForeground(new java.awt.Color(0, 89, 124));
        PcargauserINFO.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 260, 10));

        jSeparator20.setForeground(new java.awt.Color(0, 89, 124));
        PcargauserINFO.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 80, 10));

        jSeparator21.setForeground(new java.awt.Color(0, 89, 124));
        PcargauserINFO.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 80, 10));

        jSeparator22.setForeground(new java.awt.Color(0, 89, 124));
        PcargauserINFO.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 80, 10));

        jSeparator23.setForeground(new java.awt.Color(0, 89, 124));
        PcargauserINFO.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 260, 10));

        PanelINFO.add(PcargauserINFO, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 910, 235));

        PtipouserINFO.setBackground(new java.awt.Color(255, 255, 255));
        PtipouserINFO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Puseraccion1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tregistro1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tregistro1.setText("Ingrese su Registro");
        Tregistro1.setBorder(null);
        Tregistro1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tregistro1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Tregistro1FocusLost(evt);
            }
        });
        jPanel1.add(Tregistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 13, 190, -1));

        Buttcargamaterias1.setBackground(new java.awt.Color(0, 89, 124));
        Buttcargamaterias1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Buttcargamaterias1.setForeground(new java.awt.Color(255, 255, 255));
        Buttcargamaterias1.setText("Carga");
        Buttcargamaterias1.setBorder(null);
        Buttcargamaterias1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttcargamaterias1ActionPerformed(evt);
            }
        });
        jPanel1.add(Buttcargamaterias1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 80, 32));

        carrerapostgrado1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        carrerapostgrado1.setText("Carrera de Postgrado");
        jPanel1.add(carrerapostgrado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        SepRegist1.setForeground(new java.awt.Color(0, 89, 124));
        jPanel1.add(SepRegist1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 39, 190, 10));

        materia1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        materia1.setText("Materias");
        jPanel1.add(materia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 35));

        registro1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registro1.setText("Registro");
        jPanel1.add(registro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, -1, -1));

        setmaterias1.setForeground(new java.awt.Color(0, 89, 124));
        jPanel1.add(setmaterias1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 180, 20));

        cargo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cargo1.setText("Cargo");
        jPanel1.add(cargo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 36));

        Tcarrerapostgrado1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tcarrerapostgrado1.setText("Ingrese su Carrera");
        Tcarrerapostgrado1.setBorder(null);
        Tcarrerapostgrado1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tcarrerapostgrado1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Tcarrerapostgrado1FocusLost(evt);
            }
        });
        jPanel1.add(Tcarrerapostgrado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 200, -1));

        Tmaterias1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tmaterias1.setText("Ingrese su Materia");
        Tmaterias1.setBorder(null);
        Tmaterias1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tmaterias1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Tmaterias1FocusLost(evt);
            }
        });
        jPanel1.add(Tmaterias1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 180, -1));

        Tcargo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tcargo1.setText("Ingrese su Cargo");
        Tcargo1.setBorder(null);
        Tcargo1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tcargo1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Tcargo1FocusLost(evt);
            }
        });
        Tcargo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tcargo1ActionPerformed(evt);
            }
        });
        jPanel1.add(Tcargo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 180, 20));

        SepCarrera1.setForeground(new java.awt.Color(0, 89, 124));
        jPanel1.add(SepCarrera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 200, 15));

        sepCargo1.setForeground(new java.awt.Color(0, 89, 124));
        jPanel1.add(sepCargo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 180, 12));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Lmateriascargadas1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Lmateriascargadas1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jScrollPane3.setViewportView(Lmateriascargadas1);

        Butteliminarmateria1.setBackground(new java.awt.Color(0, 89, 124));
        Butteliminarmateria1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Butteliminarmateria1.setForeground(new java.awt.Color(255, 255, 255));
        Butteliminarmateria1.setText("Eliminar");
        Butteliminarmateria1.setBorder(null);
        Butteliminarmateria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butteliminarmateria1ActionPerformed(evt);
            }
        });

        materiascargadas1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        materiascargadas1.setText("Materias Cargadas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(materiascargadas1)
                        .addGap(63, 63, 63)
                        .addComponent(Butteliminarmateria1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(materiascargadas1)
                    .addComponent(Butteliminarmateria1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Puseraccion1Layout = new javax.swing.GroupLayout(Puseraccion1);
        Puseraccion1.setLayout(Puseraccion1Layout);
        Puseraccion1Layout.setHorizontalGroup(
            Puseraccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Puseraccion1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(53, 53, 53))
        );
        Puseraccion1Layout.setVerticalGroup(
            Puseraccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PtipouserINFO.add(Puseraccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 270));

        Buttmodificar.setBackground(new java.awt.Color(0, 89, 124));
        Buttmodificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Buttmodificar.setForeground(new java.awt.Color(255, 255, 255));
        Buttmodificar.setText("Modificar");
        Buttmodificar.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        Buttmodificar.setMaximumSize(new java.awt.Dimension(160, 95));
        Buttmodificar.setMinimumSize(new java.awt.Dimension(160, 95));
        Buttmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtmodificarActionPerformed(evt);
            }
        });
        PtipouserINFO.add(Buttmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 160, 44));

        PanelINFO.add(PtipouserINFO, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 910, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 942, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelINFO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 6, Short.MAX_VALUE)
                    .addComponent(PanelINFO, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

public void mostrarPersona(Persona persona) {
    if (persona == null) return;

    // Mostrar panel general
    PtipouserINFO.setVisible(true);

    // Ocultar todos los campos por defecto
    SepRegist1.setVisible(false);
    sepCargo1.setVisible(false);
    SepCarrera1.setVisible(false);
    setmaterias1.setVisible(false);
    registro1.setVisible(false);
    Tregistro1.setVisible(false);
    carrerapostgrado1.setVisible(false);
    Tcarrerapostgrado1.setVisible(false);
    cargo1.setVisible(false);
    Tcargo1.setVisible(false);
    materia1.setVisible(false);
    Tmaterias1.setVisible(false);
    Buttcargamaterias1.setVisible(false);
    jScrollPane3.setVisible(false);
    Lmateriascargadas1.setVisible(false);
    materiascargadas1.setVisible(false);
    Butteliminarmateria1.setVisible(false);
    jPanel1.setVisible(false);
    jPanel2.setVisible(false);
    // Campos comunes a todos
    Tnombre1.setText(persona.getNbre());
    Tdocumento1.setText(persona.getDoc());
    Tdireccion1.setText(persona.getDir());
    int[] fechaNac = persona.getfNac();
    Tdia1.setText(String.valueOf(fechaNac[0]));
    Tmes1.setText(String.valueOf(fechaNac[1]));
    Tanio1.setText(String.valueOf(fechaNac[2]));
    
    // Desactivar campos para que no se puedan editar
    Tnombre1.setEditable(false);
    Tdocumento1.setEditable(false);
    Tdireccion1.setEditable(false);
    Tdia1.setEditable(false);
    Tmes1.setEditable(false);
    Tanio1.setEditable(false);
    Tfacultad1.setEditable(false);
    Tcarrera1.setEditable(false);
    Tdiaing1.setEditable(false);
    Tmesing1.setEditable(false);
    Tanioing1.setEditable(false);
    Tregistro1.setEditable(false);
    Tcarrerapostgrado1.setEditable(false);
    Tcargo1.setEditable(false);
    Tmaterias1.setEditable(false);

    // Desactivar el combo de tipo de persona
    Stipopersona1.setEnabled(false);
        jPanel1.setVisible(true);
    jPanel2.setVisible(true);
    if (persona instanceof PersUniv pu) {
        Tfacultad1.setText(pu.getFac());
        Tcarrera1.setText(pu.getCar());
        int[] fechaIng = pu.getfIng();
        Tdiaing1.setText(String.valueOf(fechaIng[0]));
        Tmesing1.setText(String.valueOf(fechaIng[1]));
        Tanioing1.setText(String.valueOf(fechaIng[2]));
    }

    if (persona instanceof Alumno alumno) {
        Stipopersona1.setSelectedItem("Alumno");
        SepRegist1.setVisible(true);
        registro1.setVisible(true);
        Tregistro1.setVisible(true);
        Tregistro1.setText(alumno.getReg());
    }

    if (persona instanceof AlumnoPostGrado postgrado) {
        Stipopersona1.setSelectedItem("Alumno de Postgrado");
        SepRegist1.setVisible(true);
        SepCarrera1.setVisible(true);
        registro1.setVisible(true);
        Tregistro1.setVisible(true);
        Tregistro1.setText(postgrado.getReg());
        carrerapostgrado1.setVisible(true);
        Tcarrerapostgrado1.setVisible(true);
        Tcarrerapostgrado1.setText(postgrado.getcarPos());
    }

    if (persona instanceof Docente docente) {
        Stipopersona1.setSelectedItem("Docente");
        cargo1.setVisible(true);
        Tcargo1.setVisible(true);
        sepCargo1.setVisible(true);
        Tcargo1.setText(docente.getCargo());

        jScrollPane3.setVisible(true);
        Lmateriascargadas1.setVisible(true);
        materiascargadas1.setVisible(true);
        // Cargar materias al modelo del JList
        modeloMaterias.clear();
        for (String mat : docente.getMat()) {
            modeloMaterias.addElement(mat);
        }
    }

    PtipouserINFO.revalidate();
    PtipouserINFO.repaint();
}
    private void eXitINFOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eXitINFOMouseClicked
     this.setVisible(false);
     
    }//GEN-LAST:event_eXitINFOMouseClicked

    private void eXitINFOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eXitINFOMouseEntered
       eXitINFO.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        eXitINFO.setBackground(Color.white);
        X.setForeground(Color.RED);
    }//GEN-LAST:event_eXitINFOMouseEntered

    private void eXitINFOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eXitINFOMouseExited
        eXitINFO.setBackground(new Color(0,89,124));
        X.setForeground(Color.white);
    }//GEN-LAST:event_eXitINFOMouseExited

    private void HeaderINFOMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderINFOMouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouseINFO,y- yMouseINFO);

    }//GEN-LAST:event_HeaderINFOMouseDragged

    private void HeaderINFOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderINFOMouseClicked
        xMouseINFO = evt.getX();
        yMouseINFO = evt.getY();
    }//GEN-LAST:event_HeaderINFOMouseClicked

    private void Tnombre1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tnombre1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Tnombre1FocusGained

    private void Tnombre1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tnombre1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Tnombre1FocusLost

    private void Tnombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tnombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tnombre1ActionPerformed

    private void Tdocumento1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tdocumento1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Tdocumento1FocusGained

    private void Tdocumento1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tdocumento1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Tdocumento1FocusLost

    private void Tdia1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tdia1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Tdia1FocusGained

    private void Tdia1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tdia1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Tdia1FocusLost

    private void Tmes1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tmes1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Tmes1FocusGained

    private void Tmes1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tmes1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Tmes1FocusLost

    private void Tanio1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tanio1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Tanio1FocusGained

    private void Tanio1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tanio1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Tanio1FocusLost

    private void Tdireccion1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tdireccion1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Tdireccion1FocusGained

    private void Tdireccion1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tdireccion1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Tdireccion1FocusLost

    private void Tdireccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tdireccion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tdireccion1ActionPerformed

    private void Tfacultad1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tfacultad1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Tfacultad1FocusGained

    private void Tfacultad1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tfacultad1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Tfacultad1FocusLost

    private void Tfacultad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tfacultad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tfacultad1ActionPerformed

    private void Tcarrera1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tcarrera1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Tcarrera1FocusGained

    private void Tcarrera1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tcarrera1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Tcarrera1FocusLost

    private void Tcarrera1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tcarrera1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tcarrera1ActionPerformed

    private void Tmesing1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tmesing1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Tmesing1FocusGained

    private void Tmesing1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tmesing1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Tmesing1FocusLost

    private void Tanioing1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tanioing1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Tanioing1FocusGained

    private void Tanioing1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tanioing1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Tanioing1FocusLost

    private void Tdiaing1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tdiaing1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Tdiaing1FocusGained

    private void Tdiaing1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tdiaing1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Tdiaing1FocusLost

    private void Tdiaing1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tdiaing1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tdiaing1ActionPerformed

    private void Stipopersona1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Stipopersona1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Stipopersona1ActionPerformed

    private void Tregistro1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tregistro1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Tregistro1FocusGained

    private void Tregistro1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tregistro1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Tregistro1FocusLost

    private void Tcargo1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tcargo1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Tcargo1FocusGained

    private void Tcargo1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tcargo1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Tcargo1FocusLost

    private void Tcargo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tcargo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tcargo1ActionPerformed

    private void Tcarrerapostgrado1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tcarrerapostgrado1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Tcarrerapostgrado1FocusGained

    private void Tcarrerapostgrado1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tcarrerapostgrado1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Tcarrerapostgrado1FocusLost

    private void Tmaterias1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tmaterias1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Tmaterias1FocusGained

    private void Tmaterias1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tmaterias1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Tmaterias1FocusLost

    private void Buttcargamaterias1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttcargamaterias1ActionPerformed
        String materia = Tmaterias1.getText().trim();
        if (!materia.isEmpty()) {
            // Agregar la materia al modelo
            modeloMaterias.addElement(materia);

            // Mostrar en consola la materia que se ha cargado
            System.out.println("Materia cargada: " + materia);

            // Actualizar el JList para asegurarse de que se refleje el cambio
            Lmateriascargadas1.revalidate();   // Actualiza el JList
            Lmateriascargadas1.repaint();      // Repinta el JList

            // Actualizar el JScrollPane
            jScrollPane3.revalidate();        // Actualiza el JScrollPane
            jScrollPane3.repaint();           // Repinta el JScrollPane

            // Limpiar el campo de texto para nuevas entradas
            Tmaterias1.setText("");
            Butteliminarmateria1.setVisible(true);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese una materia.");
        }
    }//GEN-LAST:event_Buttcargamaterias1ActionPerformed

    private void Butteliminarmateria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butteliminarmateria1ActionPerformed
        int indiceSeleccionado = Lmateriascargadas1.getSelectedIndex();  // obtiene el índice seleccionado
        if (indiceSeleccionado != -1) {
            modeloMaterias.removeElementAt(indiceSeleccionado);  // elimina del modelo
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una materia para eliminar.");
        }
    }//GEN-LAST:event_Butteliminarmateria1ActionPerformed

    private void ButtmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtmodificarActionPerformed
            // Habilitar campos comunes
        Tnombre1.setEditable(true);
        Tdocumento1.setEditable(true);
        Tdireccion1.setEditable(true);
        Tdia1.setEditable(true);
        Tmes1.setEditable(true);
        Tanio1.setEditable(true);
        Tfacultad1.setEditable(true);
        Tcarrera1.setEditable(true);
        Tdiaing1.setEditable(true);
        Tmesing1.setEditable(true);
        Tanioing1.setEditable(true);

        Tmaterias1.setEditable(false);
        Buttcargamaterias1.setEnabled(false);
        Butteliminarmateria1.setEnabled(false);
        Lmateriascargadas1.setEnabled(false);
        // NO permitir modificar el tipo de persona
        Stipopersona1.setEnabled(false);

        // Según el tipo de persona, habilitar campos específicos
        String tipo = (String) Stipopersona1.getSelectedItem();
        if (tipo.equals("Alumno")) {
            Tregistro1.setEditable(true);
        } else if (tipo.equals("Alumno de Postgrado")) {
            Tregistro1.setEditable(true);
            Tcarrerapostgrado1.setEditable(true);
        } else if (tipo.equals("Docente")) {
    Tcargo1.setEditable(true);

    // Asegurarse que todos los elementos estén visibles
    materia1.setVisible(true);
    Tmaterias1.setVisible(true);
    Tmaterias1.setEnabled(true);
    Buttcargamaterias1.setVisible(true);
    Buttcargamaterias1.setEnabled(true);
    Butteliminarmateria1.setVisible(true);
    Butteliminarmateria1.setEnabled(true);
    jScrollPane3.setVisible(true);
    Lmateriascargadas1.setVisible(true);
    Lmateriascargadas1.setEnabled(true);
    materiascargadas1.setVisible(true);
        }
        JOptionPane.showMessageDialog(this, "Puede editar los campos. Recuerde guardar los cambios.");
    }//GEN-LAST:event_ButtmodificarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buttcargamaterias1;
    private javax.swing.JButton Butteliminarmateria1;
    private javax.swing.JButton Buttmodificar;
    private javax.swing.JPanel HeaderINFO;
    private javax.swing.JLabel LabDatos;
    private javax.swing.JList<String> Lmateriascargadas1;
    private javax.swing.JPanel PanelINFO;
    private javax.swing.JPanel PcargauserINFO;
    private javax.swing.JPanel PtipouserINFO;
    private javax.swing.JPanel Puseraccion1;
    private javax.swing.JSeparator SepCarrera1;
    private javax.swing.JSeparator SepRegist1;
    private javax.swing.JComboBox<String> Stipopersona1;
    private javax.swing.JTextField Tanio1;
    private javax.swing.JTextField Tanioing1;
    private javax.swing.JTextField Tcargo1;
    private javax.swing.JTextField Tcarrera1;
    private javax.swing.JTextField Tcarrerapostgrado1;
    private javax.swing.JTextField Tdia1;
    private javax.swing.JTextField Tdiaing1;
    private javax.swing.JTextField Tdireccion1;
    private javax.swing.JTextField Tdocumento1;
    private javax.swing.JTextField Tfacultad1;
    private javax.swing.JTextField Tmaterias1;
    private javax.swing.JTextField Tmes1;
    private javax.swing.JTextField Tmesing1;
    private javax.swing.JTextField Tnombre1;
    private javax.swing.JTextField Tregistro1;
    private javax.swing.JLabel X;
    private javax.swing.JLabel cargo1;
    private javax.swing.JLabel carrera1;
    private javax.swing.JLabel carrerapostgrado1;
    private javax.swing.JLabel direccion1;
    private javax.swing.JLabel documento1;
    private javax.swing.JPanel eXitINFO;
    private javax.swing.JLabel facultad1;
    private javax.swing.JLabel fechaingreso1;
    private javax.swing.JLabel fechanacimiento1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel materia1;
    private javax.swing.JLabel materiascargadas1;
    private javax.swing.JLabel nombre1;
    private javax.swing.JLabel registro1;
    private javax.swing.JSeparator sepCargo1;
    private javax.swing.JSeparator setmaterias1;
    private javax.swing.JLabel tipopersona1;
    // End of variables declaration//GEN-END:variables
}
